services:
  transactions-db:
    build:
      context: ./docker/postgres-db
    environment:
      - POSTGRES_USER=finance_db_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=finance_db
    volumes:
        - pg-data:/var/lib/postgresql/data
        - "${PWD}/db-scripts/initialize_db_ddl.sql:/docker-entrypoint-initdb.d/initialize_db_ddl.sql"
        - "${PWD}/db-scripts/initialize_analytics_ddl.sql:/docker-entrypoint-initdb.d/initialize_analytics_ddl.sql"  # new ddl for analytics schema
        - "${PWD}/db-scripts/populate_analytics_dim_dates_table.sql:/docker-entrypoint-initdb.d/populate_analytics_dim_dates_table.sql"  # query to populate the dim_date table of the new schema
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "wal_level=logical", "-c", "hot_standby=on"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  kafka-connect:
    image: debezium/connect:2.4
    depends_on:
      - kafka
      - transactions-db
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
    ports:
      - "8083:8083"

  debezium-init:
    image: curlimages/curl:latest
    depends_on:
      - kafka-connect
    volumes:
      - "${PWD}/debezium/init-connectors.sh:/init-connectors.sh"
      - "${PWD}/debezium/connectors:/connectors"
    entrypoint: ["/bin/sh", "/init-connectors.sh"]
    restart: "no"

    # NEW streaming pipeline service
  streaming-pipeline:
    build:
      context: .
      dockerfile: ./pipeline/Dockerfile
    container_name: acme_streaming_pipeline
    restart: always
    environment:
      KAFKA_BROKER: kafka:29092
      ANALYTICAL_DB_URL: "postgresql://finance_db_user:1234@transactions-db:5432/finance_db"
    depends_on:
      - kafka
      - transactions-db

  analytics-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ANALYTICAL_DB_URL=postgresql://finance_db_user:1234@transactions-db:5432/finance_db
    depends_on:
      - transactions-db
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pg-data:
